export { default as ArrowLeftShort} from './arrow-left-short.svg'
export {default as Avatar} from './Avatar.svg'
export {default as AttendanceReport} from './attendanceReport.svg'
export {default as Close} from './close.svg'
export {default as Bell} from './icons8-bell.svg'